export const data = [
  {
    image: "",
    piename: "Cheese Cake13",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/chesecakes",
  },
  {
    image: "",
    piename: "Cheese Cake12",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/chesecakes",
  },
  {
    image: "",
    piename: "Cheese Cake11",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/chesecakes",
  },
  {
    image: "",
    piename: "Fruit Cake10",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/fruitpies",
  },
  {
    image: "",
    piename: "Fruit Cake9",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/fruitpies",
  },
  {
    image: "",
    piename: "Cheese Cake8",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/fruitpies",
  },
  {
    image: "",
    piename: "Fruit Cake7",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/fruitpies",
  },
  {
    image: "",
    piename: "Cheese Cake6",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/fruitpies",
  },
  {
    image: "",
    piename: "Cheese Cake5",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/fruitpies",
  },
  {
    image: "",
    piename: "Season Cake4",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/seasonalpies",
  },
  {
    image: "",
    piename: "Sesason Cake3",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/seasonalpies",
  },
  {
    image: "",
    piename: "Season Cake2",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/seasonalpies",
  },
  {
    image: "",
    piename: "Season Cake1",
    discription: "Plain Cheese Cake",
    Price: "150$",
    cetagory: "/allpies",
    specific: "/seasonalpies",
  },
];
